name: Greetings

on: [pull_request, issues]

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secret.GITHUB_TOKEN }}
        issue-message: 'Congrast on your first issue!'
        pr-message: 'Congrast on your first pull request!'
